name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"
      - run: yarn install --immutable
        env:
          GH_TOKEN: ${{ secrets.READ_GH_PACKAGES_TOKEN }}
      - run: yarn prettier --check .
  type_check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"
      - run: yarn install --immutable
        env:
          GH_TOKEN: ${{ secrets.READ_GH_PACKAGES_TOKEN }}
      - run: yarn type-check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"
      - run: yarn install --immutable
        env:
          GH_TOKEN: ${{ secrets.READ_GH_PACKAGES_TOKEN }}
          SANITY_API_READ_TOKEN: ${{ env.SANITY_API_READ_TOKEN }}
          ANALYZE: false
          NEXT_PUBLIC_VERCEL_GIT_PROVIDER: github
          NEXT_PUBLIC_VERCEL_GIT_REPO_OWNER: ${{ env.NEXT_PUBLIC_VERCEL_GIT_REPO_OWNER }}
          NEXT_PUBLIC_VERCEL_GIT_REPO_SLUG: ${{ env.NEXT_PUBLIC_VERCEL_GIT_REPO_SLUG }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ env.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ env.NEXT_PUBLIC_SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_API_VERSION: ${{ env.NEXT_PUBLIC_SANITY_API_VERSION }}
          NEXT_PUBLIC_VERCEL_URL: ${{ env.NEXT_PUBLIC_VERCEL_URL }}
          NEXT_PUBLIC_VERCEL_ENV: ${{ env.NEXT_PUBLIC_VERCEL_ENV }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_FORMS_API: ${{ env.NEXT_PUBLIC_FORMS_API }}
      - run: yarn lint
        env:
          SKIP_ENV_CHECK: true
  conflict_check:
    name: Conflict check
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'has conflicts'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
